site_name: 'Checkov'
site_description: ''
repo_url: 'https://github.com/bridgecrewio/checkov-theme-2/'
repo_name: 'GitHub'
docs_dir: 'index/'
site_dir: '_site_mkdocs/'
theme: 'checkov-theme-2'
prev_next_buttons_location: 'both'
copyright: 'bridgecrew'
