site_name: 'Yor'
site_description: ''
repo_url: 'https://github.com/bridgecrewio/yor-theme/'
repo_name: 'GitHub'
docs_dir: 'index/'
site_dir: '_site_mkdocs/'
theme: 'yor-theme'
prev_next_buttons_location: 'both'
copyright: 'bridgecrew'
